var _globalObjectives = new Array();

var root = new Activity('242a95d5_cdc6_42a0_ac4f_4f8596614986', 'FaceBook Combined 1-4');root.Description = '';root.CompletionSetByContent = false;
                        root.ObjectiveSetByContent = false;
                        root.Tracked = true;root.Sequencing.ControlMode.Choice = true;
                        root.Sequencing.ControlMode.ChoiceExit = true;
                        root.Sequencing.ControlMode.Flow = true;
                        root.Sequencing.ControlMode.ForwardOnly = false;
                        root.Sequencing.ControlMode.UseCurrentAttemptObjectiveInfo = true;
                        root.Sequencing.ControlMode.UseCurrentAttemptProgressInfo = true;root.Sequencing.LimitConditions.AttemptLimit = 0;
                        root.Sequencing.LimitConditions.AttemptAbsoluteDurationLimit = '00:00:00';root.Sequencing.RandomizationControls.RandomizationTiming = Timing.Never;
                        root.Sequencing.RandomizationControls.SelectCount = 0;
                        root.Sequencing.RandomizationControls.ReorderChildren = false;
                        root.Sequencing.RandomizationControls.SelectionTiming = Timing.Never;root.Sequencing.ConstrainedChoiceConsiderations.PreventActivation = false;
                        root.Sequencing.ConstrainedChoiceConsiderations.ConstrainChoice = false;root.Sequencing.RollupConsiderations.RequiredForSatisfied = RollupConsiderationsToken.Always;
                        root.Sequencing.RollupConsiderations.RequiredForNotSatisfied = RollupConsiderationsToken.Always;
                        root.Sequencing.RollupConsiderations.RequiredForCompleted = RollupConsiderationsToken.Always;
                        root.Sequencing.RollupConsiderations.RequiredForIncomplete =RollupConsiderationsToken. Always;
                        root.Sequencing.RollupConsiderations.MeasureSatisfactionIfActive = true;root.Sequencing.PrimaryObjective = new TrackingModelObjective('242a95d5_cdc6_42a0_ac4f_4f8596614986_completed', root);root.Sequencing.PrimaryObjective.Identifier = 'c405b059_2c82_4b24_ae28_a61e7e2e124b_completed';root.Sequencing.PrimaryObjective.SatisfiedByMeasure = true;root.Sequencing.PrimaryObjective.MinNormalizedMeasure = 0;var root_c405b059_2c82_4b24_ae28_a61e7e2e124b_completed = root.Sequencing.PrimaryObjective;root.Sequencing.RollupRules.RollupObjectiveSatisfied = true;
                        root.Sequencing.RollupRules.RollupProgressCompletion = true;
                        root.Sequencing.RollupRules.ObjectiveMeasureWeight = 1;var root_0 = new Activity('6e34709a_0bb4_4aa9_8f46_51975230470f', 'Combined 1-4 - DCharron Evaluation Mode');root_0.Description = '';root_0.IsVisible = true;root_0.OpenInNewWindow = false;root_0.CompletionThreshold.CompletedByMeasure = false;
                    root_0.CompletionThreshold.MinProgressMeasure = 1;
                    root_0.CompletionThreshold.ProgressWeight = 1;root_0.Path = '6e34709a_0bb4_4aa9_8f46_51975230470f/index.htm';root_0.CompletionSetByContent = true;
                        root_0.ObjectiveSetByContent = true;
                        root_0.Tracked = true;root_0.Sequencing.ControlMode.Choice = true;
                        root_0.Sequencing.ControlMode.ChoiceExit = true;
                        root_0.Sequencing.ControlMode.Flow = false;
                        root_0.Sequencing.ControlMode.ForwardOnly = false;
                        root_0.Sequencing.ControlMode.UseCurrentAttemptObjectiveInfo = true;
                        root_0.Sequencing.ControlMode.UseCurrentAttemptProgressInfo = true;root_0.Sequencing.LimitConditions.AttemptLimit = 0;
                        root_0.Sequencing.LimitConditions.AttemptAbsoluteDurationLimit = '00:00:00';root_0.Sequencing.RandomizationControls.RandomizationTiming = Timing.Never;
                        root_0.Sequencing.RandomizationControls.SelectCount = 0;
                        root_0.Sequencing.RandomizationControls.ReorderChildren = false;
                        root_0.Sequencing.RandomizationControls.SelectionTiming = Timing.Never;root_0.Sequencing.ConstrainedChoiceConsiderations.PreventActivation = false;
                        root_0.Sequencing.ConstrainedChoiceConsiderations.ConstrainChoice = false;root_0.Sequencing.RollupConsiderations.RequiredForSatisfied = RollupConsiderationsToken.Always;
                        root_0.Sequencing.RollupConsiderations.RequiredForNotSatisfied = RollupConsiderationsToken.Always;
                        root_0.Sequencing.RollupConsiderations.RequiredForCompleted = RollupConsiderationsToken.Always;
                        root_0.Sequencing.RollupConsiderations.RequiredForIncomplete =RollupConsiderationsToken. Always;
                        root_0.Sequencing.RollupConsiderations.MeasureSatisfactionIfActive = true;root_0.Sequencing.PrimaryObjective = new TrackingModelObjective('6e34709a_0bb4_4aa9_8f46_51975230470f_completed', root_0);root_0.Sequencing.PrimaryObjective.Identifier = '6e34709a_0bb4_4aa9_8f46_51975230470f_completed';root_0.Sequencing.PrimaryObjective.SatisfiedByMeasure = true;root_0.Sequencing.PrimaryObjective.MinNormalizedMeasure = 0;var root_0_6e34709a_0bb4_4aa9_8f46_51975230470f_completed = root_0.Sequencing.PrimaryObjective;root_0.Sequencing.RollupRules.RollupObjectiveSatisfied = true;
                        root_0.Sequencing.RollupRules.RollupProgressCompletion = true;
                        root_0.Sequencing.RollupRules.ObjectiveMeasureWeight = 1;root.Add(root_0);